# -*- coding: utf-8 -*-
"""recommendation_syaytem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LCJmZJ5ybJb0QMp-OPjyzCF5EprpqBp5
"""

#mount the csv file
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

file_path="/content/Movie.csv"
movies_df=pd.read_csv(file_path)
movies_df.head()

movies_df.info()

movies_df.describe()

moives_df.shape

moives_df[0:5]

len(moives_df.userId.unique())

len(moives_df.movie.unique())

user_movies_df = movies_df.pivot(index='userId',
                                 columns='movie',
                                 values='rating').reset_index(drop=True)
user_movies_df

user_movies_df.fillna(0,inplace=True)
user_movies_df

user_sim=1-pd.DataFrame()
user_sim_df

import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

from google.colab import drive
drive.mount('/content/drive')

file_name="/content/Titanic.csv"

titanic_df=pd.read_csv(file_name)
titanic_df.head()

